import Testimonials from "@/app/_components/page_components/Testimonials";
import Bredcumb from "@/app/_components/page_components/Bredcumb";

export const metadata = {
  title: "Synergy |  Terms & Conditions",
  description: "Your Strategic Partner for Business Excellence",
};

const content = `<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">These terms and conditions (&ldquo;Terms&rdquo;, &ldquo;Agreement&rdquo;) are an agreement between SYNERGY FIN. CONSULTING (&ldquo;SYNERGY FIN. CONSULTING&rdquo;, &ldquo;us&rdquo;, &ldquo;we&rdquo; or &ldquo;our&rdquo;) and you (&ldquo;User&rdquo;, &ldquo;you&rdquo; or &ldquo;your&rdquo;). This Agreement sets forth the general terms and conditions of your use of the&nbsp;<a style="box-sizing: border-box; color: #008ec6; text-decoration-line: none; cursor: pointer; outline-style: none; transition: 200ms cubic-bezier(0.785, 0.135, 0.15, 0.86); margin-bottom: 0px;" href="http://www.peerise.com/" aria-invalid="true">consultsynergy.ae</a> website and any of its products or services (collectively, &ldquo;Website&rdquo; or &ldquo;Services&rdquo;).</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">User content</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">We do not own any data, information or material (&ldquo;Content&rdquo;) that you submit on the Website in the course of using the Service. You shall have sole responsibility for the accuracy, quality, integrity, legality, reliability, appropriateness, and intellectual property ownership or right to use of all submitted Content. We may monitor and review Content on the Website submitted or created using our Services by you. Unless specifically permitted by you, your use of the Website does not grant us the license to use, reproduce, adapt, modify, publish or distribute the Content created by you or stored in your user account for commercial, marketing or any similar purpose. But you grant us permission to access, copy, distribute, store, transmit, reformat, display and perform the Content of your user account solely as required for the purpose of providing the Services to you. Without limiting any of those representations or warranties, we have the right, though not the obligation, to, in our own sole discretion, refuse or remove any Content that, in our reasonable opinion, violates any of our policies or is in any way harmful or objectionable.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Accuracy of information</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">Occasionally there may be information on the Website that contains typographical errors, inaccuracies or omissions that may relate to promotions and offers. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information on the Website or on any related Service is inaccurate at any time without prior notice (including after you have submitted your order). We undertake no obligation to update, amend or clarify information on the Website including, without limitation, pricing information, except as required by law. No specified update or refresh date applied on the Website should be taken to indicate that all information on the Website or on any related Service has been modified or updated.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Backups</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">We perform regular backups of the Website and Content and will do our best to ensure completeness and accuracy of these backups. In the event of the hardware failure or data loss we will restore backups automatically to minimize the impact and downtime.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Advertisements</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">During use of the Website, you may enter into correspondence with or participate in promotions of advertisers or sponsors showing their goods or services through the Website. Any such activity, and any terms, conditions, warranties or representations associated with such activity, is solely between you and the applicable third-party. We shall have no liability, obligation or responsibility for any such correspondence, purchase or promotion between you and any such third-party.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Links to other websites</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">Although this Website may link to other websites, we are not, directly or indirectly, implying any approval, association, sponsorship, endorsement, or affiliation with any linked website, unless specifically stated herein. Some of the links on the Website may be &ldquo;affiliate links&rdquo;. This means if you click on the link and purchase an item, SYNERGY FIN. CONSULTING will receive an affiliate commission. We are not responsible for examining or evaluating, and we do not warrant the offerings of, any businesses or individuals or the content of their websites. We do not assume any responsibility or liability for the actions, products, services, and content of any other third-parties. You should carefully review the legal statements and other conditions of use of any website which you access through a link from this Website. Your linking to any other off-site websites is at your own risk.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Prohibited uses</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">In addition to other terms as set forth in the Agreement, you are prohibited from using the Website or its Content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Intellectual property rights</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">This Agreement does not transfer to you any intellectual property owned by SYNERGY FIN. CONSULTING or third-parties, and all rights, titles, and interests in and to such property will remain (as between the parties) solely with SYNERGY FIN. CONSULTING. All trademarks, service marks, graphics and logos used in connection with our Website or Services, are trademarks or registered trademarks of SYNERGY FIN. CONSULTING or SYNERGY FIN. CONSULTING licensors. Other trademarks, service marks, graphics and logos used in connection with our Website or Services may be the trademarks of other third-parties. Your use of our Website and Services grants you no right or license to reproduce or otherwise use any SYNERGY FIN. CONSULTING or third-party trademarks.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Disclaimer of warranty</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">You agree that your use of our Website or Services is solely at your own risk. You agree that such Service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. We expressly disclaim all warranties of any kind, whether express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose and non-infringement. We make no warranty that the Services will meet your requirements, or that the Service will be uninterrupted, timely, secure, or error-free; nor do we make any warranty as to the results that may be obtained from the use of the Service or as to the accuracy or reliability of any information obtained through the Service or that defects in the Service will be corrected. You understand and agree that any material and/or data downloaded or otherwise obtained through the use of Service is done at your own discretion and risk and that you will be solely responsible for any damage to your computer system or loss of data that results from the download of such material and/or data. We make no warranty regarding any goods or services purchased or obtained through the Service or any transactions entered into through the Service. No advice or information, whether oral or written, obtained by you from us or through the Service shall create any warranty not expressly made herein.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Limitation of liability</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">To the fullest extent permitted by applicable law, in no event will SYNERGY FIN. CONSULTING, its affiliates, officers, directors, employees, agents, suppliers or licensors be liable to any person for (a): any indirect, incidental, special, punitive, cover or consequential damages (including, without limitation, damages for lost profits, revenue, sales, goodwill, use of content, impact on business, business interruption, loss of anticipated savings, loss of business opportunity) however caused, under any theory of liability, including, without limitation, contract, tort, warranty, breach of statutory duty, negligence or otherwise, even if SYNERGY FIN. CONSULTING has been advised as to the possibility of such damages or could have foreseen such damages. To the maximum extent permitted by applicable law, the aggregate liability of SYNERGY FIN. CONSULTING and its affiliates, officers, employees, agents, suppliers and licensors, relating to the services will be limited to an amount greater of one dollar or any amounts actually paid in cash by you to SYNERGY FIN. CONSULTING for the prior one month period prior to the first event or occurrence giving rise to such liability. The limitations and exclusions also apply if this remedy does not fully compensate you for any losses or fails of its essential purpose.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Indemnification</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">You agree to indemnify and hold SYNERGY FIN. CONSULTING and its affiliates, directors, officers, employees, and agents harmless from and against any liabilities, losses, damages or costs, including reasonable attorneys&rsquo; fees, incurred in connection with or arising from any third-party allegations, claims, actions, disputes, or demands asserted against any of them as a result of or relating to your Content, your use of the Website or Services or any willful misconduct on your part.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Severability</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">All rights and restrictions contained in this Agreement may be exercised and shall be applicable and binding only to the extent that they do not violate any applicable laws and are intended to be limited to the extent necessary so that they will not render this Agreement illegal, invalid or unenforceable. If any provision or portion of any provision of this Agreement shall be held to be illegal, invalid or unenforceable by a court of competent jurisdiction, it is the intention of the parties that the remaining provisions or portions thereof shall constitute their agreement with respect to the subject matter hereof, and all such remaining provisions or portions thereof shall remain in full force and effect.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Dispute resolution</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">The formation, interpretation, and performance of this Agreement and any disputes arising out of it shall be governed by the substantive and procedural laws of United Arab Emirates without regard to its rules on conflicts or choice of law and, to the extent applicable, the laws of United Arab Emirates. The exclusive jurisdiction and venue for actions related to the subject matter hereof shall be the courts located in United Arab Emirates, and you hereby submit to the personal jurisdiction of such courts. You hereby waive any right to a jury trial in any proceeding arising out of or related to this Agreement. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Assignment</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">You may not assign, resell, sub-license or otherwise transfer or delegate any of your rights or obligations hereunder, in whole or in part, without our prior written consent, which consent shall be at our own sole discretion and without obligation; any such assignment or transfer shall be null and void. We are free to assign any of its rights or obligations hereunder, in whole or in part, to any third-party as part of the sale of all or substantially all of its assets or stock or as part of a merger.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Changes and amendments</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">We reserve the right to modify this Agreement or its policies relating to the Website or Services at any time, effective upon posting of an updated version of this Agreement on the Website. When we do, we will revise the updated date at the bottom of this page. Continued use of the Website after any such changes shall constitute your consent to such changes.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Acceptance of these terms</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">You acknowledge that you have read this Agreement and agree to all its terms and conditions. By using the Website or its Services you agree to be bound by this Agreement. If you do not agree to abide by the terms of this Agreement, you are not authorized to use or access the Website and its Services.</p>
<h2 style="box-sizing: border-box; font-family: Poppins, Arial, Helvetica, sans-serif; font-weight: 500; line-height: 44px; color: #252525; margin-top: 0px; margin-bottom: 7px; font-size: 34px; padding: 0px; text-rendering: optimizelegibility; white-space: normal; background-color: #ffffff;">Contacting us</h2>
<p style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">If you would like to contact us to understand more about this Agreement or wish to contact us concerning any matter relating to it, you may send an email to info@consultsynergy.ae</p>
<p style="box-sizing: border-box; margin: 0px; padding: 0px; color: #616a66; font-family: Poppins, arial, sans-serif; font-size: 15px; white-space: normal; background-color: #ffffff;">This document was last updated on April 25, 2020</p>`;

export default async function PageTerms() {
  let APIURL = process.env.NEXT_PUBLIC_API_BASE_URL;
  const { data } = await fetch(`${APIURL}/cms/pages/csr`, {
    cache: "no-store",
  }).then((res) => res.json());

  return (
    <>
      <section className={`banner-section`}>
        <div className="inner-banner">
          <div className="inner-banner-bg">
            <img src="/img/inner-banner.png" />
          </div>
          <div className="single-banner">
            <div className="container">
              <div className="row justify-content-center align-items-center">
                <div className="col-lg-12 col-md-12 text-left">
                  <div className="inner-banner-content">
                    <div className="h_w">
                      <h1 data-animation="fadeInUp" data-delay="1s">
                        {" "}
                        Terms & Conditions
                      </h1>
                    </div>
                    <Bredcumb title="Terms & Conditions" />
                  </div>
                </div>
              </div>

              <div className="row justify-content-center align-items-center">
                <div className="col-lg-12 col-md-12">
                  <div className="inner-banner-img">
                    <img src="/img/csr.png" alt="Terms & Conditions" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="inner-content-section section-gap csr_page">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-4">
              <div className="inner-content-title">
                <h5> Terms & Conditions</h5>
              </div>
            </div>
            <div className="col-lg-8">
              <div className="inner-content-box">
                <div
                  dangerouslySetInnerHTML={{
                    __html: content,
                  }}
                ></div>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* <Testimonials /> */}
    </>
  );
}
